install_test_deps: &install_test_deps
  name: install dependencies
  command: |
    sudo pip install pipenv tox
    pipenv sync -d

run_tox: &run_tox
  name: run tests
  command: tox

submit_coverage: &submit_coverage
  name: submit coverage
  command: pipenv run coveralls

package: &package
  name: generate packages
  command: pipenv run python setup.py sdist bdist_wheel

pypi_upload: &pypi_upload
  name: upload packages to Pypi
  command: pipenv run twine upload dist/*

build_steps: &build_steps
- checkout

# Download and cache dependencies
- restore_cache:
    keys:
    - v1-tox

- run: *install_test_deps

- run: *run_tox

# Save tox and venv cache
- save_cache:
    paths:
    - ./.tox
    key: v1-tox

version: 2
jobs:
  test_36:
    docker:
    - image: circleci/python:3.6
      environment:
        TOXENV=py36
    working_directory: ~/repo
    steps:
      <<: *build_steps
      - persist_to_workspace:
          root: ~/repo
          paths:
          - .coverage

  test_37:
    docker:
    - image: circleci/python:3.7
      environment:
        TOXENV=py37
    working_directory: ~/repo
    steps:
      <<: *build_steps

  test_flake:
    docker:
    - image: circleci/python:3.6
      environment:
        TOXENV=flake8
    working_directory: ~/repo
    steps:
      <<: *build_steps

  submit_coverage:
    docker:
    - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-venv
    - run: *install_test_deps
    - attach_workspace:
        at: /tmp/dir
    - run:
        name: Copy coverage over
        command: cp /tmp/dir/.coverage .
    - run: *submit_coverage


  distribute:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-venv
    - run: *install_test_deps
    - run: *package
    - run: *pypi_upload

workflows:
  version: 2
  build-distribute:
    jobs:
    - test_36:
        filters:
          tags:
            only: /.*/ # This is needed so that tags are also built when pushed

    - test_37:
        filters:
          tags:
            only: /.*/ # This is needed so that tags are also built when pushed

    - test_flake:
        filters:
          tags:
            only: /.*/ # This is needed so that tags are also built when pushed

    - submit_coverage:
        requires:
        - test_36
        - test_37
        - test_flake
        filters:
          tags:
            only: /.*/

    - distribute:
        requires:
        - test_36
        - test_37
        - test_flake
        filters:
          branches:
            only: master
          tags:
            only: /^v.*/
